import { Iform } from "../iquote";

export const createquoteFrom:Iform={
    fields: [
        {
          key: 'quoteBy',
          type: 'input',
          templateOptions: {
            label: 'Enter The Name Of Quotee',
          },
        },
        {
            key: 'createdBy',
            type: 'input',
            templateOptions: {
              label: 'Quote Generated By',
          
            },
          },
        {
          key: 'quote',
          type: 'input',
          templateOptions: {
            label: 'Enter The Quote',
            type:'textarea',
            cols: 20
          },
        },

        {
            key: 'aboutQuoteCreator',
            type: 'input',
            templateOptions: {
              label: 'Describe The Quote Creator',
              type:'textarea',
              cols: 20
            },
          },
         
      ]
}